### ISSUE TITLE
path planning 

### ISSUE THREAD

**Issue by python-developer-m06** [LiaoSteve/Drone-GCS-and-AI#1]
i really like your work.but i dont know why u dont use path planning algorithm to hit spacific target

**Comment by LiaoSteve** [comment]
This is just a fuzzy obstacle avoidance test and these obstacles are unknown to the drone. My drone goes to the waypoints where I give before takeoff.

**Comment by LiaoSteve** [comment]
> i really like your work.but i dont know why u dont use path planning algorithm to hit spacific target

This is just a fuzzy obstacle avoidance test and these obstacles are unknown to the drone. My drone goes to the waypoints where I give before takeoff.
