### ISSUE TITLE
Paper request

### ISSUE THREAD

**Issue by miayemaw** [LiaoSteve/Drone-GCS-and-AI#3]
Hello..

First of all , thanks for the great framework  and not the issue in the code )) ... I just want to ask you some question , first one is can i get the following paper if you have ?

 "T. H. Huang, "Path Planning and Visual Obstacle Avoidance Based on Fuzzy Theory for UAV Apllication," 2020 "

And in your airsim path planning, do u use any path planner? 

thanks..

**Comment by LiaoSteve** [comment]
Hi @miarmoh 

I'm a coworker of  T. H. Huang,  This paper "Path Planning and Visual Obstacle Avoidance Based on Fuzzy Theory for UAV Applications," 2020 " will public on [National Taiwan Ocean University](http://ethesys.lib.ntou.edu.tw/cgi-bin/cdrfb3/gsweb.cgi?o=dstdcdr) after 2 years at least .

You can contact to T.H. Huang (黃宗賢) via mail : ntou10767013@gmail.com

**Comment by miayemaw** [comment]
Thanks.. i m contacting T.H.Huang...
